#!/usr/bin/env sh

set -e

if [ -z "$1" ]; then
  echo "Enter a file name." >&2
  exit
fi

if [ -z "$VIEWER" ]; then
  VIEWER="links"
fi

if ! head -c 4 "$1" | grep -q "%PDF"; then
  echo "$1 is not a PDF." >&2
  exit
fi

DATE=$(date +%s)

if [ ! -d "/tmp/bpdf" ]; then
  mkdir /tmp/bpdf
fi

mutool convert -o /tmp/bpdf/$DATE.html -F html "$1"

command -v "$VIEWER" >/dev/null 2>&1 || { echo "Links is not installed." >&2; exit; }
"$VIEWER" "/tmp/bpdf/$DATE.html"
rm "/tmp/bpdf/$DATE.html" -f
